version: 0.0
os: linux
files:
  - source: /
    destination: /opt/tomcat/tomcat9
    permissions:
      - object: /opt/tomcat/tomcat9/bin/catalina.sh
        pattern: catalina.sh
        mode: "0755"  # Set the desired permission mode here (e.g., 0755 for execute permission)
hooks:
  AfterInstall:
    - location: /opt/tomcat/tomcat9/bin/catalina.sh
      timeout: 300
      runas: root
